spring:
  application:
    name: player-service
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8000

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 3s